create table usage (application text, entry text, timestamp datetime);
insert into usage (application, entry, timestamp) values ("testapp.desktop", "One", datetime('now', 'utc'));
insert into usage (application, entry, timestamp) values ("testapp.desktop", "Two", datetime('now', 'utc'));
insert into usage (application, entry, timestamp) values ("testapp.desktop", "Two", datetime('now', 'utc', '-1 day'));
insert into usage (application, entry, timestamp) values ("testapp.desktop", "Three", datetime('now', 'utc'));
insert into usage (application, entry, timestamp) values ("testapp.desktop", "Three", datetime('now', 'utc', '-1 day'));
insert into usage (application, entry, timestamp) values ("testapp.desktop", "Three", datetime('now', 'utc', '-2 day'));
insert into usage (application, entry, timestamp) values ("testapp.desktop", "Four", datetime('now', 'utc'));
insert into usage (application, entry, timestamp) values ("testapp.desktop", "Four", datetime('now', 'utc', '-1 day'));
insert into usage (application, entry, timestamp) values ("testapp.desktop", "Four", datetime('now', 'utc', '-2 day'));
insert into usage (application, entry, timestamp) values ("testapp.desktop", "Four", datetime('now', 'utc', '-3 day'));
