'\" t
.\"     Title: hud-cli
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 01/17/2012
.\"    Manual: User Commands
.\"    Source: User Commands
.\"  Language: English
.\"
.TH "HUD\-CLI" "1" "01/17/2012" "User Commands" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
hud-cli \- Tool to exercise the HUD on the command line
.SH "SYNOPSIS"
.HP \w'\fBhud\-cli\fR\ 'u
\fBhud\-cli\fR
.HP \w'\fBhud\-cli\fR\ 'u
\fBhud\-cli\fR \fIsearch\ string\fR
.SH "AUTHOR"
.PP
Written by Ted Gould
ted@canonical\&.com
and others\&.
.SH "BUGS"
.PP
Bugs should be submitted to Launchpad:
\m[blue]\fB\%https://bugs.launchpad.net/indicator-appmenu/+filebug\fR\m[]
