'\" t
.\"     Title: hud-dump-application
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 01/27/2012
.\"    Manual: User Commands
.\"    Source: User Commands
.\"  Language: English
.\"
.TH "HUD\-DUMP\-APPLICATI" "1" "01/27/2012" "User Commands" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
hud-dump-application \- Tool to dump information on an application from the HUD usage database
.SH "SYNOPSIS"
.HP \w'\fBhud\-dump\-application\fR\ 'u
\fBhud\-dump\-application\fR \fIdesktop\ file\ path\fR
.SH "AUTHOR"
.PP
Written by Ted Gould
ted@canonical\&.com
and others\&.
.SH "BUGS"
.PP
Bugs should be submitted to Launchpad:
\m[blue]\fB\%https://bugs.launchpad.net/indicator-appmenu/+filebug\fR\m[]
.SH "SEE ALSO"
.PP

\fBhud-list-applications\fR(1)
