const char * hud_interface = 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<node name=\"/\">\n"
"	<interface name=\"com.canonical.hud\">\n"
"<!-- Properties -->\n"
"		<!-- None -->\n"
"\n"
"<!-- Functions -->\n"
"		<method name=\"GetSuggestions\">\n"
"			<arg type=\"s\" name=\"query\" direction=\"in\" />\n"
"			<arg type=\"s\" name=\"icon\" direction=\"out\" />\n"
"			<arg type=\"s\" name=\"target\" direction=\"out\" />\n"
"			<arg type=\"a(ssv)\" name=\"suggestions\" direction=\"out\" />\n"
"		</method>\n"
"\n"
"		<method name=\"ExecuteQuery\">\n"
"			<arg type=\"v\" name=\"key\" direction=\"in\" />\n"
"			<arg type=\"u\" name=\"timestamp\" direction=\"in\" />\n"
"		</method>\n"
"\n"
"<!-- Signals -->\n"
"		<!-- None -->\n"
"\n"
"<!-- End of interesting stuff -->\n"
"\n"
"	</interface>\n"
"</node>\n"
;
