const char * hud_interface = 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<node name=\"/\">\n"
"	<interface name=\"com.canonical.hud\">\n"
"<!-- Properties -->\n"
"		<!-- None -->\n"
"\n"
"<!-- Functions -->\n"
"		<method name=\"StartQuery\">\n"
"			<!-- in -->\n"
"			<arg type=\"s\" name=\"query\" direction=\"in\" />\n"
"			<arg type=\"i\" name=\"entries\" direction=\"in\" />\n"
"			<!-- out -->\n"
"			<arg type=\"s\" name=\"target\" direction=\"out\" />\n"
"			<arg type=\"a(sssssv)\" name=\"suggestions\" direction=\"out\" />\n"
"			<arg type=\"v\" name=\"querykey\" direction=\"out\" />\n"
"		</method>\n"
"\n"
"		<method name=\"ExecuteQuery\">\n"
"			<arg type=\"v\" name=\"key\" direction=\"in\" />\n"
"			<arg type=\"u\" name=\"timestamp\" direction=\"in\" />\n"
"		</method>\n"
"\n"
"		<method name=\"CloseQuery\">\n"
"			<arg type=\"v\" name=\"querykey\" direction=\"in\" />\n"
"		</method>\n"
"\n"
"<!-- Signals -->\n"
"		<signal name=\"UpdatedQuery\">\n"
"			<arg type=\"s\" name=\"target\" direction=\"out\" />\n"
"			<arg type=\"a(sssssv)\" name=\"suggestions\" direction=\"out\" />\n"
"			<arg type=\"v\" name=\"querykey\" direction=\"out\" />\n"
"		</method>\n"
"\n"
"<!-- End of interesting stuff -->\n"
"\n"
"	</interface>\n"
"</node>\n"
;
